apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: db-health-check

resources:
  - ../../base/deployment.yaml

images:
  - name: db-health-check
    newName: example.azurecr.io/db-health-check
    newTag: replace-with-ci-commit-sha
